name: demo-actions

on:
  push:
     branches: main


jobs:
  build:
   runs-on: ubuntu-latest
   steps: 
   - uses: actions/checkout@v4
   
   - name : run a sampel
     run : echo "hello word"
   

     
