name: demo-actions

on:
  push:
     branches: main


jobs:
  build:
   runs-on: ubuntu-latest
   steps: 
   - uses: actions/checkout@v4
   
   - name : run a sampel
     run : echo "hello word"

  deploy:
     runs-on: ubuntu-latest
     steps: 

         -uses: actions/download-artifact@4
          with: 
              name: build-artifact
              path: ${{github.workspace}}
   

     
