name: demo-actions

on:
  push:
     branches: main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
   
    - name : run a sampel
      run : echo "hello word"
      
    - uses: actions/upload-artifact@v4
      with: 
        name: build-artifact
        path: ${{github.workspace}}


  deploy:
     runs-on: ubuntu-latest
     needs: build
     steps: 

        - uses: actions/download-artifact@v4
          with: 
            name: build-artifact
            path: ${{github.workspace}}
   

     
